# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "checkout-ui"
client_id = "d5ad7e3c28b059e9d6d8092d48139eaa"
application_url = "https://ambien-allocated-gift-wisconsin.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ambien-allocated-gift-wisconsin.trycloudflare.com/auth/callback",
  "https://ambien-allocated-gift-wisconsin.trycloudflare.com/auth/shopify/callback",
  "https://ambien-allocated-gift-wisconsin.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "grtcheckoutui.myshopify.com"
